c1:
	g++ -std=c++17 001.cpp && ./a.out && rm ./a.out
c2:
	g++ -std=c++17 002.cpp && ./a.out && rm ./a.out
c3:
	g++ -std=c++17 003.cpp && ./a.out && rm ./a.out
c4:
	g++ -std=c++17 004.cpp && ./a.out && rm ./a.out