c1:
	g++ -std=c++17 001.cpp && ./a.out && rm ./a.out
c2:
	g++ -std=c++17 002.cpp && ./a.out && rm ./a.out
c3:
	g++ -std=c++17 003.cpp && ./a.out && rm ./a.out
c4:
	g++ -std=c++17 004.cpp && ./a.out && rm ./a.out
c5:
	g++ -std=c++17 005.cpp && ./a.out && rm ./a.out
c6:
	g++ -std=c++17 006.cpp && ./a.out && rm ./a.out
c7:
	g++ -std=c++17 007.cpp && ./a.out && rm ./a.out