th:
	g++ -std=c++20 -pthread c1.cpp -o teo && ./teo && rm ./teo
c1:
	g++ -std=c++20 -pthread c1.cpp -o c1 && ./c1 && rm ./c1
c2:
	g++ -std=c++20 -pthread c2.cpp -o c2 && ./c2 && rm ./c2
c3:
	g++ -std=c++20 -pthread c3.cpp -o c3 && ./c3 && rm ./c3
c5:
	g++ -std=c++20 -pthread c5.cpp -o c5 && ./c5 && rm ./c5
