c1:
	g++ -std=c++20 c1.cpp && ./a.out && rm ./a.out
c2:
	g++ -std=c++14 c2.cpp c2.h && ./a.out && rm ./a.out
c3:
	g++ -std=c++17 c3.cpp c3.h && ./a.out && rm ./a.out
c4:
	g++ -std=c++17 c4.cpp c4.h && ./a.out && rm ./a.out
c5:
	g++ -std=c++17 c5.cpp c5.h && ./a.out && rm ./a.out
c6:
	g++ -std=c++17 c6.cpp && ./a.out && rm ./a.out
c7:
	g++ -std=c++17 c7.cpp && ./a.out && rm ./a.out
c8:
	g++ -std=c++17 c8.cpp && ./a.out && rm ./a.out
clean:
	find . -name "*.h.gch" | xargs rm