p1: 
	g++ -std=c++20 001.cpp && ./a.out && rm ./a.out
p2: 
	g++ -std=c++20 002.cpp && ./a.out && rm ./a.out
p3: 
	g++ -std=c++20 003.cpp && ./a.out && rm ./a.out
p4: 
	g++ -std=c++20 004.cpp && ./a.out && rm ./a.out
p5: 
	g++ -std=c++20 005.cpp && ./a.out && rm ./a.out
p6: 
	g++ -std=c++20 006.cpp && ./a.out && rm ./a.out
