t1:
	g++ -std=c++20 teo.cpp && ./a.out && rm ./a.out
c1:
	g++ -std=c++20 c1.cpp && ./a.out && rm ./a.out
c2:
	g++ -std=c++14 c2.cpp && ./a.out && rm ./a.out
c3:
	g++ -std=c++17 c3.cpp && ./a.out && rm ./a.out
c4:
	g++ -std=c++17 c4.cpp && ./a.out && rm ./a.out
c5:
	g++ -std=c++17 c5.cpp && ./a.out && rm ./a.out