teo:
	g++ -std=c++20 teo.cpp && ./a.out && rm ./a.out
teo2:
	g++ -std=c++20 teo2.cpp && ./a.out && rm ./a.out
teo33:
	g++ -std=c++20 teo3.cpp && ./a.out && rm ./a.out
c1:
	g++ -std=c++20 001.cpp && ./a.out && rm ./a.out
c2:
	g++ -std=c++20 002.cpp && ./a.out && rm ./a.out
c3:
	g++ -std=c++20 003.cpp && ./a.out && rm ./a.out
c4:
	g++ -std=c++20 004.cpp && ./a.out && rm ./a.out
c5:
	g++ -std=c++20 005.cpp && ./a.out && rm ./a.out
c6:
	g++ -std=c++20 006.cpp && ./a.out && rm ./a.out
c7:
	g++ -std=c++17 007.cpp && ./a.out && rm ./a.out
c8:
	g++ -std=c++17 008.cpp && ./a.out && rm ./a.out
c9:
	g++ -std=c++17 009.cpp && ./a.out && rm ./a.out