c1:
	g++ -std=c++20 001.cpp && ./a.out && rm ./a.out
c2:
	g++ -std=c++20 002.cpp && ./a.out && rm ./a.out
c3:
	g++ -std=c++20 003.cpp && ./a.out && rm ./a.out
c4:
	g++ -std=c++20 004.cpp && ./a.out && rm ./a.out