p1:
	g++ -std=c++17 p1.cpp p1.h && ./a.out && rm ./a.out
p2:
	g++ -std=c++17 p2.cpp p2.h && ./a.out && rm ./a.out
p3:
	g++ -std=c++17 p3.cpp p3.h && ./a.out && rm ./a.out
p4:
	g++ -std=c++17 p4.cpp p4.h && ./a.out && rm ./a.out
p5:
	g++ -std=c++17 p5.cpp p5.h && ./a.out && rm ./a.out
p6:
	g++ -std=c++17 p6.cpp p6.h && ./a.out && rm ./a.out

